databases:
  - name: postgresql
    databaseName: alpha_blog_qp2u
    user: alphablog

services:
  - type: web
    name: alpha-blog
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alpha-blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false